name: FamCam
favicon: null
layout_spectrum: 0.75018
typography_spectrum: 0.60924
title: FamCam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74862152-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c8c8c8'
    - '#000000'
    - '#004ba5'
    - '#aa8071'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
