name: FamCam
favicon: null
layout_spectrum: 0.87956
typography_spectrum: 0.60924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.40934546501375735
  lightness: 0.7804893711581826
  saturation: 0.9541875850409269
  rhythmicContrast: 0.9095845124684274
purpose: []
