name: FamCam
favicon: null
layout_spectrum: 0.56573
typography_spectrum: 0.60924
title: FamCam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74862152-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c8c8c8'
    - '#000000'
    - '#004ba5'
    - '#aa8071'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
